apiVersion: v2
name: atradius-controller
description: A Helm chart for Atradius Ingress Controller
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: ingress-nginx
  version: "4.11.2"
  repository: "https://kubernetes.github.io/ingress-nginx"